### ISSUE TITLE
@HasQualifierParameter on JDK collections behaves differently from user defined collections

### ISSUE THREAD

**Issue by t-rasmud** [t-rasmud/checker-framework#160]
Consider this test case:

```
import java.util.Collection;
import org.checkerframework.checker.determinism.qual.CollectionType;
import org.checkerframework.checker.determinism.qual.Det;
import org.checkerframework.checker.determinism.qual.NonDet;
import org.checkerframework.checker.determinism.qual.OrderNonDet;
import org.checkerframework.framework.qual.HasQualifierParameter;

public class CollectionHasQualParam {
    void test(@OrderNonDet MyCollection<@Det String> c) {}

    void test1(@OrderNonDet Collection<@Det String> c) {}
}

@SuppressWarnings("invalid.upper.bound.on.type.argument")
@HasQualifierParameter(NonDet.class)
@CollectionType
interface MyCollection<T> {}
```

and the following declaration of `Collection` in the JDK:

```
@HasQualifierParameter(NonDet.class)
@CollectionType
public interface Collection<E> extends Iterable<E> 
```

Running the determinism checker with the command: `/javac -processor determinism checker/tests/determinism/CollectionHasQualParam.java` produces the following unexpected error:

```
checker/tests/determinism/CollectionHasQualParam.java:11: error: [ordernondet.on.noncollection.and.nonarray] @OrderNonDet annotation is invalid for non-collections and non-arrays
    void test1(@OrderNonDet Collection<@Det String> c) {}
                                                    ^
1 error
```

`MyCollection<T>` and the `Collection` class in JDK are annotated with `@HasQualifierParameter` and `CollectionType`. However, the checker issues an error only in the case of JDK Collection.

Find this test case and built JDK [here](https://github.com/t-rasmud/checker-framework/tree/hasQualParamIssue).

**Comment by smillst** [comment]
Try rebuilding the JDK.  I ran `javap -v Collection.class` on the classfile in the jdk8.jar, and it did not have any determinism annotations.

**Comment by t-rasmud** [comment]
Thanks. I rebuilt the JDK and made another commit. Strangely, `javap -v Collection.class` doesn't show any determinism annotations but other classes do (I tried on `ArrayList.class`)! Is there something I am missing?

**Comment by smillst** [comment]
Here's the problem:
https://travis-ci.org/t-rasmud/checker-framework/jobs/646613653#L14498
```
java.lang.IllegalArgumentException: value interface org.checkerframework.checker.determinism.qual.NonDet
	at org.objectweb.asmx.ClassWriter.newConstItem(ClassWriter.java:994)
	at org.objectweb.asmx.AnnotationWriter.visit(AnnotationWriter.java:185)
	at scenelib.annotations.io.classfile.ClassAnnotationSceneWriter.visitFields(ClassAnnotationSceneWriter.java:388)
	at scenelib.annotations.io.classfile.ClassAnnotationSceneWriter.ensureVisitSceneClassAnnotations(ClassAnnotationSceneWriter.java:245)
	at scenelib.annotations.io.classfile.ClassAnnotationSceneWriter.visitMethod(ClassAnnotationSceneWriter.java:190)
	at org.objectweb.asmx.ClassReader.accept(ClassReader.java:862)
	at org.objectweb.asmx.ClassReader.accept(ClassReader.java:445)
	at scenelib.annotations.io.classfile.ClassFileWriter.insert(ClassFileWriter.java:186)
	at scenelib.annotations.io.classfile.ClassFileWriter.main(ClassFileWriter.java:132)
Please submit a bug report at
  https://github.com/typetools/annotation-tools/issues
```

**Comment by t-rasmud** [comment]
Related bug fixed in annotation-tools.
